@echo off
echo Starting USB Guard Streamlit Dashboard...
echo ----------------------------------------
echo Activating Virtual Environment...
call venv\Scripts\activate
echo Running Streamlit App...
streamlit run streamlit_app.py
pause
